database.driver = "mysql"
database.dsn = "root:root@tcp(127.0.0.1:3306)/vengo_test"
database.max-open-conns = 10
database.max-idle-conns = 5
database.conn-max-lifetime = "5m"
database.conn-max-idle-time = "1m"
database.slow-query-threshold = "1ms"
database.migrations-table = "schema_migrations"
database.migrations-path-prefix = "migrations"
